const STORAGE_KEY = 'juniorImportsV3Data';
const DEFAULT_ADMIN_PIN = '1234';
const CART_KEY = 'juniorImportsV3Cart';
const FAVORITES_KEY = 'juniorImportsV3Favorites';

const iconSet = ['✦','✓','⚡','◈'];
const clone = value => JSON.parse(JSON.stringify(value));
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const uid = prefix => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const safe = (value = '') => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const money = value => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const dateBR = value => new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));
const slugify = value => String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');

const BASE_PRODUCTS = [
  ['tg15','T.G. 15','Tirzepatida','TG Labs',649.90,719.90,18,'Mais vendido','#1677ff'],
  ['lipoland15','Lipoland 15 mg','Tirzepatida','Lipoland',619.90,689.90,12,'Oferta','#0a73ff'],
  ['lipoless15','Lipoless MD 15','Tirzepatida','Lipoless',599.90,659.90,22,'Destaque','#2684ff'],
  ['tirzec15','TirZec 15','Tirzepatida','TirZec',629.90,699.90,9,'Últimas unidades','#2b6cff'],
  ['slimex15','Slimex 15','Tirzepatida','Slimex',579.90,639.90,28,'','#3978ff'],
  ['retagen','Retagen','Retatrutida','Retagen',749.90,829.90,14,'Novidade','#6a58d8'],
  ['retatrutide-aq120','Retatrutide AQ 120','Retatrutida','AQ Labs',799.90,879.90,8,'Premium','#765ee8'],
  ['peplab-retatrutide','PepLab Retatrutide','Retatrutida','PepLab',729.90,799.90,16,'','#8669ef'],
  ['xl-klow','XL Peptides KLOW','Peptídeos','XL Peptides',389.90,439.90,20,'Kit','#1b9688'],
  ['xl-glow','XL Peptides Glow','Peptídeos','XL Peptides',419.90,469.90,17,'Destaque','#d46a9e'],
  ['ghk-cu','GHK-Cu','Peptídeos','BioLab',299.90,349.90,31,'','#2ca0b5'],
  ['mots-c','MOTS-c','Peptídeos','BioLab',359.90,399.90,15,'','#a77c2f'],
  ['pt141','PT-141','Medicamentos','Pharma Lab',279.90,319.90,19,'Oferta','#c25475'],
  ['dysport500','Dysport 500 U','Estética profissional','Dysport',1249.90,1399.90,6,'Profissional','#5f72a8'],
  ['israderm','Israderm','Estética profissional','Israderm',459.90,519.90,11,'','#c78d68'],
  ['diluente','Diluente bacteriostático','Diluentes','Junior Imports',89.90,109.90,47,'Essencial','#4e9ac7']
].map((item,index)=>({
  id:item[0],slug:slugify(item[1]),name:item[1],category:item[2],brand:item[3],price:item[4],compareAt:item[5],stock:item[6],badge:item[7],accent:item[8],
  description:`${item[1]} em apresentação importada, selecionado para o catálogo demonstrativo da Junior Imports.`,
  sku:`JI-${String(index+1).padStart(3,'0')}`,rating:Number((4.6+(index%4)*.1).toFixed(1)),reviews:12+index*7,featured:index<8,active:true,order:index+1,image:''
}));

const DEFAULT_DATA = {
  version:3,
  settings:{
    storeName:'Junior Imports',whatsapp:'5531999999999',email:'contato@juniorimports.com.br',hours:'Segunda a sexta · 9h às 18h',
    announcement:'Frete grátis em compras acima de R$ 499',footerDescription:'Importados selecionados, ofertas exclusivas e compra rápida.',
    primaryColor:'#1677ff',freeShippingThreshold:499,shippingFlat:29.90,pixDiscount:5,adminPin:DEFAULT_ADMIN_PIN,autoBannerSeconds:6
  },
  banners:[
    {id:'banner-1',kicker:'OFERTA DA SEMANA',title:'Importados selecionados com preços especiais.',highlight:'preços especiais.',subtitle:'Monte seu carrinho, aplique o cupom e conclua um pedido demonstrativo em poucos passos.',buttonText:'Comprar agora',buttonLink:'#catalogo',start:'#07101f',end:'#0b65ef',image:'',active:true,order:1},
    {id:'banner-2',kicker:'NOVIDADES NO CATÁLOGO',title:'Produtos em destaque para sua próxima compra.',highlight:'próxima compra.',subtitle:'Conheça os lançamentos e os itens mais procurados da Junior Imports.',buttonText:'Ver destaques',buttonLink:'#destaques',start:'#160c25',end:'#765ee8',image:'',active:true,order:2},
    {id:'banner-3',kicker:'CUPOM DE PRIMEIRA COMPRA',title:'Use JUNIOR10 e ganhe 10% de desconto.',highlight:'10% de desconto.',subtitle:'Condição criada para demonstrar campanhas promocionais e cupons no checkout.',buttonText:'Usar cupom',buttonLink:'#catalogo',start:'#071d19',end:'#128a72',image:'',active:true,order:3}
  ],
  trustItems:[
    {id:'trust-1',title:'Compra rápida',subtitle:'Checkout em poucos passos'},
    {id:'trust-2',title:'Pagamento simulado',subtitle:'Pix, cartão ou boleto'},
    {id:'trust-3',title:'Frete demonstrativo',subtitle:'Grátis acima de R$ 499'},
    {id:'trust-4',title:'Suporte direto',subtitle:'Atendimento por WhatsApp'}
  ],
  categories:['Tirzepatida','Retatrutida','Peptídeos','Medicamentos','Estética profissional','Diluentes'].map((name,index)=>({id:`cat-${index+1}`,name,active:true,order:index+1})),
  sections:[
    {id:'featured',name:'Produtos em destaque',eyebrow:'DESTAQUES DA LOJA',title:'Os produtos mais procurados.',subtitle:'Seleção configurável pelo painel.',active:true,order:1},
    {id:'catalog',name:'Catálogo completo',eyebrow:'TODOS OS PRODUTOS',title:'Encontre o produto certo.',subtitle:'Busque, filtre e ordene o catálogo.',active:true,order:2},
    {id:'promo',name:'Banner promocional',eyebrow:'CONDIÇÃO ESPECIAL',title:'Frete grátis acima de R$ 499.',subtitle:'Aproveite as condições demonstrativas e finalize seu pedido em poucos passos.',buttonText:'Ver produtos',buttonLink:'#catalogo',active:true,order:3},
    {id:'benefits',name:'Benefícios',eyebrow:'POR QUE COMPRAR',title:'Uma experiência pensada para conversão.',subtitle:'',active:true,order:4},
    {id:'faq',name:'Dúvidas frequentes',eyebrow:'PRECISA DE AJUDA?',title:'Informação clara antes da compra.',subtitle:'',active:true,order:5}
  ],
  benefits:[
    {id:'benefit-1',title:'Ofertas visíveis',text:'Preço, desconto e condições apresentados diretamente no produto.'},
    {id:'benefit-2',title:'Carrinho completo',text:'Quantidade, cupom, subtotal, frete e total em uma única tela.'},
    {id:'benefit-3',title:'Checkout objetivo',text:'Formulário simples com entrega e pagamento demonstrativos.'},
    {id:'benefit-4',title:'Pedido registrado',text:'Cada simulação gera um código e fica disponível no painel.'}
  ],
  faqs:[
    {id:'faq-1',question:'As compras são reais?',answer:'Não. Este é um projeto demonstrativo. Nenhum pagamento, envio ou venda real é processado.'},
    {id:'faq-2',question:'Como funciona o checkout?',answer:'O sistema calcula cupom, frete e condição de pagamento, registra um pedido de teste e exibe um código demonstrativo.'},
    {id:'faq-3',question:'Posso alterar os produtos?',answer:'Sim. O painel permite adicionar, editar, ocultar, excluir e reorganizar produtos.'},
    {id:'faq-4',question:'Os banners são editáveis?',answer:'Sim. É possível alterar texto, link, cores, imagem, posição e visibilidade dos banners rotativos.'}
  ],
  coupons:[
    {id:'coupon-1',code:'JUNIOR10',type:'percent',value:10,min:0,active:true,expires:''},
    {id:'coupon-2',code:'PRIMEIRA25',type:'fixed',value:25,min:250,active:true,expires:''}
  ],
  products:BASE_PRODUCTS,
  orders:[
    {id:'JI-1001',createdAt:'2026-07-10T15:20:00-03:00',customer:{name:'Cliente demonstração',phone:'31999990001',email:'cliente1@exemplo.com',city:'Ipatinga',state:'MG',address:'Rua Exemplo, 100'},items:[{id:'tg15',name:'T.G. 15',quantity:1,price:649.90}],subtotal:649.90,discount:64.99,shipping:0,total:584.91,payment:'Pix',status:'Pago'},
    {id:'JI-1002',createdAt:'2026-07-11T11:45:00-03:00',customer:{name:'Maria Teste',phone:'31999990002',email:'cliente2@exemplo.com',city:'Timóteo',state:'MG',address:'Av. Demonstração, 45'},items:[{id:'xl-glow',name:'XL Peptides Glow',quantity:1,price:419.90},{id:'diluente',name:'Diluente bacteriostático',quantity:2,price:89.90}],subtotal:599.70,discount:29.99,shipping:0,total:569.71,payment:'Pix',status:'Enviado'},
    {id:'JI-1003',createdAt:'2026-07-12T18:10:00-03:00',customer:{name:'João Projeto',phone:'31999990003',email:'cliente3@exemplo.com',city:'Coronel Fabriciano',state:'MG',address:'Rua Acadêmica, 12'},items:[{id:'retagen',name:'Retagen',quantity:1,price:749.90}],subtotal:749.90,discount:0,shipping:0,total:749.90,payment:'Cartão',status:'Novo'}
  ]
};

function normalizeData(data){
  const merged={...clone(DEFAULT_DATA),...data};
  merged.settings={...clone(DEFAULT_DATA.settings),...(data?.settings||{})};
  merged.settings.adminPin=String(merged.settings.adminPin??'').trim()||DEFAULT_ADMIN_PIN;
  ['banners','trustItems','categories','sections','benefits','faqs','coupons','products','orders'].forEach(key=>{if(!Array.isArray(merged[key]))merged[key]=clone(DEFAULT_DATA[key])});
  return merged;
}
function loadData(){try{return normalizeData(JSON.parse(localStorage.getItem(STORAGE_KEY))||clone(DEFAULT_DATA))}catch{return clone(DEFAULT_DATA)}}
const state={
  data:loadData(),cart:JSON.parse(localStorage.getItem(CART_KEY)||'[]'),favorites:JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]'),
  category:'Todos',search:'',sort:'order',coupon:null,bannerIndex:0,bannerTimer:null,productQuantity:1,adminPage:'dashboard',adminEditor:null,selectedOrder:null
};
function saveData(message='Alterações salvas'){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.data));const el=$('#adminSaveStatus');if(el){el.textContent=message;setTimeout(()=>{if(el)el.textContent='Dados salvos localmente'},1200)}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(state.cart))}
function saveFavorites(){localStorage.setItem(FAVORITES_KEY,JSON.stringify(state.favorites))}
function whatsappUrl(message=''){const phone=String(state.data.settings.whatsapp||'').replace(/\D/g,'');return `https://wa.me/${phone}${message?`?text=${encodeURIComponent(message)}`:''}`}
function productById(id){return state.data.products.find(product=>product.id===id)}
function categoryNames(){return state.data.categories.filter(c=>c.active).sort((a,b)=>a.order-b.order).map(c=>c.name)}
function activeProducts(){return state.data.products.filter(p=>p.active).sort((a,b)=>a.order-b.order)}
function productImage(product){return product.image?`<img src="${safe(product.image)}" alt="${safe(product.name)}">`:productArt(product)}
function productArt(product){return `<div class="product-art" style="--product-accent:${safe(product.accent||'#1677ff')}"><div class="product-art__box"><small>${safe(product.brand||'JUNIOR IMPORTS')}</small><b>${safe(product.name)}</b><i></i></div><div class="product-art__vial">${safe(product.category)}</div></div>`}
function stockState(product){if(Number(product.stock)<=0)return['Esgotado','out'];if(Number(product.stock)<=10)return[`Só ${product.stock} unidades`,'low'];return['Em estoque','']}
function priceMarkup(product){const hasCompare=Number(product.compareAt)>Number(product.price);return `<div class="price-stack">${hasCompare?`<del>${money(product.compareAt)}</del>`:''}<strong>${money(product.price)}</strong><small>${state.data.settings.pixDiscount}% OFF no Pix</small></div>`}
function discountPercent(product){return Number(product.compareAt)>Number(product.price)?Math.round((1-Number(product.price)/Number(product.compareAt))*100):0}
function applyTheme(){document.documentElement.style.setProperty('--primary',state.data.settings.primaryColor||'#1677ff');const store=state.data.settings.storeName||'Junior Imports';const brand=$('#brandName');if(brand)brand.textContent=store.split(' ')[0].toUpperCase()}

function renderBanners(){
  const banners=state.data.banners.filter(b=>b.active).sort((a,b)=>a.order-b.order);
  const slides=$('#heroSlides'),dots=$('#heroDots');
  if(!banners.length){$('#heroCarousel').hidden=true;return}$('#heroCarousel').hidden=false;
  state.bannerIndex=Math.min(state.bannerIndex,banners.length-1);
  slides.innerHTML=banners.map((banner,index)=>{
    const title=safe(banner.title).replace(safe(banner.highlight||''),banner.highlight?`<span>${safe(banner.highlight)}</span>`:'');
    return `<article class="hero-slide ${index===state.bannerIndex?'active':''}" style="--banner-start:${safe(banner.start)};--banner-end:${safe(banner.end)}" data-banner-index="${index}">${banner.image?`<div class="hero-slide__image" style="background-image:url('${safe(banner.image)}')"></div>`:''}<div class="container hero-slide__content"><div class="hero-copy"><span class="hero-kicker">${safe(banner.kicker)}</span><h1>${title}</h1><p>${safe(banner.subtitle)}</p><div class="hero-copy__actions"><a class="button button--primary button--large" href="${safe(banner.buttonLink||'#catalogo')}">${safe(banner.buttonText||'Ver produtos')}</a><a class="button button--ghost button--large" href="${whatsappUrl('Olá! Quero saber mais sobre as ofertas da Junior Imports.')}" target="_blank" rel="noopener">Falar no WhatsApp</a></div></div></div></article>`
  }).join('');
  dots.innerHTML=banners.map((_,index)=>`<button class="hero-dot ${index===state.bannerIndex?'active':''}" data-banner-dot="${index}" aria-label="Exibir banner ${index+1}"></button>`).join('');
  clearInterval(state.bannerTimer);if(banners.length>1)state.bannerTimer=setInterval(()=>showBanner((state.bannerIndex+1)%banners.length),Math.max(3,Number(state.data.settings.autoBannerSeconds)||6)*1000)
}
function showBanner(index){const slides=$$('.hero-slide'),dots=$$('.hero-dot');if(!slides.length)return;state.bannerIndex=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle('active',i===state.bannerIndex));dots.forEach((dot,i)=>dot.classList.toggle('active',i===state.bannerIndex))}
function renderTrust(){
  $('#trustGrid').innerHTML=state.data.trustItems.map((item,index)=>`<article class="trust-item"><div class="trust-icon">${iconSet[index%iconSet.length]}</div><div><strong>${safe(item.title)}</strong><small>${safe(item.subtitle)}</small></div></article>`).join('')
}
function sectionHeading(section,link=''){return `<div class="section-heading"><div><span class="section-kicker">${safe(section.eyebrow)}</span><h2>${safe(section.title)}</h2></div>${link||section.subtitle?link||`<p>${safe(section.subtitle)}</p>`:''}</div>`}
function productCard(product){
  const [stockLabel,stockClass]=stockState(product),discount=discountPercent(product),favorite=state.favorites.includes(product.id);
  return `<article class="product-card" data-view-product="${product.id}"><div class="product-card__visual">${product.badge?`<span class="product-card__badge">${safe(product.badge)}</span>`:discount?`<span class="product-card__badge">-${discount}%</span>`:''}<button class="product-card__favorite" data-favorite="${product.id}" aria-label="${favorite?'Remover dos':'Adicionar aos'} favoritos">${favorite?'♥':'♡'}</button>${productImage(product)}<button class="product-card__quick" data-view-product="${product.id}">Ver detalhes</button></div><div class="product-card__body"><div class="product-card__meta"><span class="product-card__category">${safe(product.category)}</span><span class="stock-pill ${stockClass}">${stockLabel}</span></div><h3>${safe(product.name)}</h3><p class="product-card__desc">${safe(product.description)}</p><div class="rating">★★★★★ <span>${product.rating} (${product.reviews})</span></div><div class="product-card__bottom">${priceMarkup(product)}<button class="product-add" data-add-product="${product.id}" ${Number(product.stock)<=0?'disabled':''} aria-label="Adicionar ${safe(product.name)} ao carrinho">+</button></div></div></article>`
}
function renderFeaturedSection(section){const products=activeProducts().filter(p=>p.featured).slice(0,8);return `<section class="section" id="destaques"><div class="container">${sectionHeading(section,'<a class="text-link" href="#catalogo">Ver catálogo completo <b>→</b></a>')}<div class="featured-grid">${products.map(productCard).join('')}</div></div></section>`}
function filteredProducts(){
  let products=activeProducts();
  if(state.category!=='Todos')products=products.filter(p=>p.category===state.category);
  if(state.search){const term=state.search.toLowerCase();products=products.filter(p=>[p.name,p.category,p.brand,p.description,p.sku].some(v=>String(v).toLowerCase().includes(term)))}
  if(state.sort==='price-asc')products.sort((a,b)=>a.price-b.price);else if(state.sort==='price-desc')products.sort((a,b)=>b.price-a.price);else if(state.sort==='name')products.sort((a,b)=>a.name.localeCompare(b.name));else products.sort((a,b)=>a.order-b.order);
  return products;
}
function renderCatalogControls(){
  const categories=['Todos',...categoryNames()];
  $('#categoryFilters').innerHTML=categories.map(name=>`<button class="${state.category===name?'active':''}" data-category="${safe(name)}">${safe(name)}</button>`).join('');
  const products=filteredProducts();$('#productGrid').innerHTML=products.map(productCard).join('');$('#resultCount').textContent=`${products.length} produto${products.length===1?'':'s'}`;$('#activeFilter').textContent=state.category==='Todos'?'Todos os produtos':state.category;$('#emptyState').hidden=!!products.length
}
function renderCatalogSection(section){return `<section class="section" id="catalogo"><div class="container">${sectionHeading(section)}<div class="catalog-toolbar"><div class="category-filters" id="categoryFilters"></div><label class="select-wrap"><span>Ordenar</span><select id="sortSelect"><option value="order">Ordem da loja</option><option value="price-asc">Menor preço</option><option value="price-desc">Maior preço</option><option value="name">Nome A–Z</option></select></label></div><div class="catalog-status"><span id="resultCount"></span><span id="activeFilter"></span></div><div class="product-grid" id="productGrid"></div><div class="empty-state" id="emptyState" hidden><strong>Nenhum produto encontrado.</strong><p>Tente outro termo ou categoria.</p><button class="button button--ghost" id="clearFilters">Limpar filtros</button></div></div></section>`}
function renderPromoSection(section){return `<section class="section"><div class="container"><div class="promo-card"><div><span class="section-kicker">${safe(section.eyebrow)}</span><h2>${safe(section.title)}</h2><p>${safe(section.subtitle)}</p></div><a class="button button--light button--large" href="${safe(section.buttonLink||'#catalogo')}">${safe(section.buttonText||'Ver produtos')}</a></div></div></section>`}
function renderBenefitsSection(section){return `<section class="section" id="beneficios"><div class="container">${sectionHeading(section)}<div class="benefits-grid">${state.data.benefits.map((item,index)=>`<article class="benefit-card"><span>0${index+1}</span><h3>${safe(item.title)}</h3><p>${safe(item.text)}</p></article>`).join('')}</div></div></section>`}
function renderFaqSection(section){return `<section class="section" id="duvidas"><div class="container faq-grid"><div><span class="section-kicker">${safe(section.eyebrow)}</span><h2>${safe(section.title)}</h2></div><div class="faq-list">${state.data.faqs.map((faq,index)=>`<details ${index===0?'open':''}><summary>${safe(faq.question)}</summary><p>${safe(faq.answer)}</p></details>`).join('')}</div></div></section>`}
function renderSections(){
  const renderers={featured:renderFeaturedSection,catalog:renderCatalogSection,promo:renderPromoSection,benefits:renderBenefitsSection,faq:renderFaqSection};
  $('#homeSections').innerHTML=state.data.sections.filter(s=>s.active).sort((a,b)=>a.order-b.order).map(section=>renderers[section.id]?.(section)||'').join('');
  if($('#categoryFilters')){renderCatalogControls();$('#sortSelect').value=state.sort}
}
function applySettings(){
  applyTheme();const s=state.data.settings;$('#announcementText').textContent=s.announcement;$('#footerDescription').textContent=s.footerDescription;$('#footerHours').textContent=s.hours;$('#footerEmail').textContent=s.email;['footerWhatsapp','whatsappFloat'].forEach(id=>{$(`#${id}`).href=whatsappUrl('Olá! Vim pelo e-commerce demonstrativo da Junior Imports.')});
}
function renderStore(){applySettings();renderBanners();renderTrust();renderSections();renderCart()}

function cartMetrics(payment=''){
  let subtotal=0;state.cart.forEach(item=>{const p=productById(item.id);if(p)subtotal+=Number(p.price)*item.quantity});
  let discount=0;if(state.coupon){discount=state.coupon.type==='percent'?subtotal*(Number(state.coupon.value)/100):Number(state.coupon.value);discount=Math.min(discount,subtotal)}
  if(payment==='Pix')discount+=Math.max(0,subtotal-discount)*(Number(state.data.settings.pixDiscount)/100);
  const after=Math.max(0,subtotal-discount),shipping=after>=Number(state.data.settings.freeShippingThreshold)?0:Number(state.data.settings.shippingFlat),total=after+shipping;
  return {subtotal,discount,shipping,total,items:state.cart.reduce((sum,item)=>sum+item.quantity,0)}
}
function addToCart(id,quantity=1){const p=productById(id);if(!p||!p.active||p.stock<=0)return;const item=state.cart.find(i=>i.id===id);const current=item?.quantity||0;const next=Math.min(Number(p.stock),current+Number(quantity));if(item)item.quantity=next;else state.cart.push({id,quantity:Math.min(Number(quantity),Number(p.stock))});saveCart();renderCart();toast(`${p.name} adicionado ao carrinho.`)}
function updateCart(id,delta){const item=state.cart.find(i=>i.id===id),p=productById(id);if(!item||!p)return;item.quantity=Math.max(0,Math.min(Number(p.stock),item.quantity+delta));if(!item.quantity)state.cart=state.cart.filter(i=>i.id!==id);saveCart();renderCart()}
function removeCart(id){state.cart=state.cart.filter(i=>i.id!==id);saveCart();renderCart()}
function renderCart(){
  const m=cartMetrics();$('#cartCount').textContent=m.items;$('#checkoutButton').disabled=!state.cart.length;
  $('#cartItems').innerHTML=state.cart.length?state.cart.map(item=>{const p=productById(item.id);if(!p)return'';return `<div class="cart-item"><div class="cart-item__art">${p.image?`<img src="${safe(p.image)}" alt="">`:'JI'}</div><div><h4>${safe(p.name)}</h4><div class="cart-item__price">${money(p.price*item.quantity)}</div><div class="qty-control"><button data-cart-minus="${p.id}">−</button><span>${item.quantity}</span><button data-cart-plus="${p.id}">+</button></div></div><button class="cart-item__remove" data-cart-remove="${p.id}" aria-label="Remover">×</button></div>`}).join(''):`<div class="cart-empty"><div><svg viewBox="0 0 24 24"><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.7a2 2 0 0 0 2-1.5L21 7H7" fill="none" stroke="currentColor" stroke-width="1.5"/></svg><strong>Seu carrinho está vazio.</strong><p>Adicione produtos para continuar.</p></div></div>`;
  $('#cartSubtotal').textContent=money(m.subtotal);$('#cartDiscountRow').hidden=!m.discount;$('#cartDiscount').textContent=`− ${money(m.discount)}`;$('#cartTotal').textContent=money(m.total);$('#cartShipping').textContent=m.shipping?money(m.shipping):'Grátis'
}
function applyCoupon(){const code=$('#cartCouponInput').value.trim().toUpperCase(),m=cartMetrics();const coupon=state.data.coupons.find(c=>c.active&&c.code.toUpperCase()===code&&(!c.expires||new Date(c.expires)>=new Date())&&m.subtotal>=Number(c.min||0));if(!coupon){state.coupon=null;$('#cartCouponMessage').textContent='Cupom inválido, expirado ou abaixo do valor mínimo.';$('#cartCouponMessage').style.color='var(--danger)'}else{state.coupon=coupon;$('#cartCouponMessage').textContent=`Cupom ${coupon.code} aplicado.`;$('#cartCouponMessage').style.color='var(--green)'}renderCart()}
function openDrawer(){renderCart();$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closeDrawer(){$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');document.body.classList.remove('locked')}
function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false');document.body.classList.add('locked')}
function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true');if(!$('.drawer.open')&&!$('.modal.open'))document.body.classList.remove('locked')}
function openProduct(id){const p=productById(id);if(!p)return;state.productQuantity=1;const [stockLabel,stockClass]=stockState(p);$('#productModalContent').innerHTML=`<div class="product-modal-grid"><div class="product-modal-visual" style="--product-accent:${safe(p.accent)}">${productImage(p)}</div><div class="product-modal-details"><button class="close-button" data-close="product" aria-label="Fechar">×</button><span>${safe(p.category)} · ${safe(p.brand)}</span><h3 id="productModalTitle">${safe(p.name)}</h3><div class="rating">★★★★★ <span>${p.rating} · ${p.reviews} avaliações</span></div><p>${safe(p.description)}</p><div class="modal-price">${priceMarkup(p)}</div><div class="product-info-list"><div><span>SKU</span><strong>${safe(p.sku)}</strong></div><div><span>Disponibilidade</span><strong class="stock-pill ${stockClass}">${stockLabel}</strong></div><div><span>Entrega</span><strong>Frete grátis acima de ${money(state.data.settings.freeShippingThreshold)}</strong></div></div><div class="quantity-buy"><div class="quantity-select"><button data-product-qty="minus">−</button><span id="productQty">1</span><button data-product-qty="plus">+</button></div><button class="button button--primary button--full button--large" data-modal-add="${p.id}" ${p.stock<=0?'disabled':''}>Adicionar ao carrinho</button></div></div></div>`;openModal('#productModal')}
function renderCheckout(payment='Pix'){
  const m=cartMetrics(payment);$('#checkoutReview').innerHTML=state.cart.map(item=>{const p=productById(item.id);return `<div class="checkout-summary-item"><i>JI</i><div><b>${safe(p.name)}</b><small>${item.quantity} unidade${item.quantity>1?'s':''}</small></div><strong>${money(p.price*item.quantity)}</strong></div>`}).join('')+`<div class="checkout-summary-totals"><div><span>Subtotal</span><strong>${money(m.subtotal)}</strong></div><div><span>Descontos</span><strong>− ${money(m.discount)}</strong></div><div><span>Frete</span><strong>${m.shipping?money(m.shipping):'Grátis'}</strong></div><div class="grand"><span>Total</span><strong>${money(m.total)}</strong></div></div>`
}
function openCheckout(){if(!state.cart.length)return;closeDrawer();renderCheckout('Pix');openModal('#checkoutModal')}
function createOrder(form){
  const payment=form.payment||'Pix',m=cartMetrics(payment),next=state.data.orders.reduce((max,o)=>Math.max(max,Number(String(o.id).replace(/\D/g,''))||1000),1000)+1;const id=`JI-${next}`;
  const order={id,createdAt:new Date().toISOString(),customer:{name:form.name,phone:form.phone,email:form.email,city:form.city,state:form.state,address:`${form.address}, ${form.number}${form.complement?` · ${form.complement}`:''} · CEP ${form.zip}`},items:state.cart.map(item=>{const p=productById(item.id);return{id:p.id,name:p.name,quantity:item.quantity,price:Number(p.price)}}),subtotal:m.subtotal,discount:m.discount,shipping:m.shipping,total:m.total,payment,status:'Novo',coupon:state.coupon?.code||''};
  state.data.orders.unshift(order);saveData('Pedido registrado');state.cart=[];state.coupon=null;saveCart();renderCart();return order
}
function showOrderSuccess(order){closeModal('#checkoutModal');$('#checkoutForm').reset();$('#orderSuccessContent').innerHTML=`<div class="success-icon">✓</div><h2 id="orderSuccessTitle">Pedido criado.</h2><p>Esta é uma confirmação demonstrativa. Nenhuma cobrança foi processada.</p><div class="order-code">${safe(order.id)}</div><p>Total demonstrativo: <strong>${money(order.total)}</strong></p><div class="success-actions"><a class="button button--primary button--full" href="${whatsappUrl(`Olá! Criei o pedido demonstrativo ${order.id} no valor de ${money(order.total)}.`)}" target="_blank" rel="noopener">Enviar código pelo WhatsApp</a><button class="button button--ghost button--full" data-close="success">Continuar comprando</button></div>`;openModal('#orderSuccessModal')}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];saveFavorites();renderSections()}

/* ADMIN */
const adminMeta={dashboard:['PAINEL','Visão geral'],products:['CATÁLOGO','Produtos'],banners:['PÁGINA INICIAL','Banners rotativos'],categories:['ORGANIZAÇÃO','Categorias'],sections:['PÁGINA INICIAL','Ordem das seções'],coupons:['PROMOÇÕES','Cupons'],orders:['VENDAS','Pedidos demonstrativos'],settings:['LOJA','Configurações'],data:['MANUTENÇÃO','Dados e backup']};
function openAdmin(){state.adminEditor=null;$('#adminShell').classList.add('open');$('#adminShell').setAttribute('aria-hidden','false');document.body.classList.add('locked');$('#adminLogin').hidden=false;$('#adminApp').hidden=true;$('#adminPin').value='';const error=$('#adminPinError');if(error)error.textContent='';setTimeout(()=>$('#adminPin').focus(),50)}
function enterAdmin(){
  const typed=String($('#adminPin').value||'').trim();
  const configured=String(state.data.settings.adminPin||DEFAULT_ADMIN_PIN).trim()||DEFAULT_ADMIN_PIN;
  const error=$('#adminPinError');
  if(typed!==configured&&typed!==DEFAULT_ADMIN_PIN){if(error)error.textContent='PIN incorreto. Use o PIN configurado ou o PIN de recuperação 1234.';toast('PIN incorreto.');return}
  if(error)error.textContent='';
  $('#adminLogin').hidden=true;$('#adminApp').hidden=false;renderAdmin();
}
function resetAdminPin(){state.data.settings.adminPin=DEFAULT_ADMIN_PIN;saveData('PIN redefinido');$('#adminPin').value=DEFAULT_ADMIN_PIN;enterAdmin();toast('PIN redefinido para 1234.')}
function closeAdmin(){$('#adminShell').classList.remove('open');$('#adminShell').setAttribute('aria-hidden','true');document.body.classList.remove('locked');renderStore()}
function renderAdmin(){const [eyebrow,title]=adminMeta[state.adminPage];$('#adminPageEyebrow').textContent=eyebrow;$('#adminPageTitle').textContent=title;$$('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.adminPage===state.adminPage));const renderer={dashboard:adminDashboard,products:adminProducts,banners:adminBanners,categories:adminCategories,sections:adminSections,coupons:adminCoupons,orders:adminOrders,settings:adminSettings,data:adminData}[state.adminPage];$('#adminContent').innerHTML=renderer();afterAdminRender()}
function adminDashboard(){const orders=state.data.orders,revenue=orders.reduce((s,o)=>s+Number(o.total),0),avg=orders.length?revenue/orders.length:0,active=state.data.products.filter(p=>p.active).length;const last7=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const day=d.toISOString().slice(0,10),value=orders.filter(o=>String(o.createdAt).slice(0,10)===day).reduce((s,o)=>s+o.total,0);return{label:d.toLocaleDateString('pt-BR',{weekday:'short'}).slice(0,3),value}});const max=Math.max(...last7.map(x=>x.value),1);return `<div class="admin-grid-stats"><article class="stat-card"><span>PRODUTOS ATIVOS</span><strong>${active}</strong><small>${state.data.products.length-active} ocultos</small></article><article class="stat-card"><span>PEDIDOS</span><strong>${orders.length}</strong><small>${orders.filter(o=>o.status==='Novo').length} novos</small></article><article class="stat-card"><span>RECEITA SIMULADA</span><strong>${money(revenue)}</strong><small>Todos os pedidos</small></article><article class="stat-card"><span>TICKET MÉDIO</span><strong>${money(avg)}</strong><small>Valor demonstrativo</small></article></div><section class="admin-panel"><div class="admin-panel__head"><div><h2>Receita dos últimos 7 dias</h2><p>Pedidos demonstrativos registrados no navegador.</p></div></div><div class="admin-panel__body"><div class="chart-bars">${last7.map(x=>`<div class="chart-bar" style="height:${Math.max(4,(x.value/max)*100)}%"><span>${x.label}</span></div>`).join('')}</div></div></section><section class="admin-panel"><div class="admin-panel__head"><div><h2>Pedidos recentes</h2><p>Últimas simulações realizadas.</p></div><button class="admin-button" data-admin-go="orders">Ver todos</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Total</th><th>Status</th></tr></thead><tbody>${orders.slice(0,6).map(order=>`<tr><td><strong>${safe(order.id)}</strong></td><td>${safe(order.customer.name)}</td><td>${dateBR(order.createdAt)}</td><td>${money(order.total)}</td><td>${orderStatusTag(order.status)}</td></tr>`).join('')}</tbody></table></div></section>`}
function orderStatusTag(status){const cls=status==='Novo'?'pending':status==='Cancelado'?'off':'';return `<span class="status-tag ${cls}">${safe(status)}</span>`}
function adminProducts(){const editing=state.adminEditor?.type==='product'?productEditor(state.adminEditor.id):'';return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Catálogo de produtos</h2><p>Adicione, edite, oculte e defina a ordem de exibição.</p></div><div class="admin-actions"><button class="admin-button primary" data-new-product>Adicionar produto</button></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th></th><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Destaque</th><th>Status</th><th>Ações</th></tr></thead><tbody>${state.data.products.sort((a,b)=>a.order-b.order).map(p=>`<tr draggable="true" data-product-row="${p.id}"><td><span class="drag-handle">⋮⋮</span></td><td><div style="display:flex;align-items:center;gap:9px"><div class="admin-product-thumb">${p.image?`<img src="${safe(p.image)}" alt="">`:'JI'}</div><div><strong>${safe(p.name)}</strong><br><small>${safe(p.sku)}</small></div></div></td><td>${safe(p.category)}</td><td>${money(p.price)}</td><td>${p.stock}</td><td>${p.featured?'Sim':'Não'}</td><td><span class="status-tag ${p.active?'':'off'}">${p.active?'Ativo':'Oculto'}</span></td><td><div class="admin-table-actions"><button class="admin-button small" data-move-product="up" data-id="${p.id}">↑</button><button class="admin-button small" data-move-product="down" data-id="${p.id}">↓</button><button class="admin-button small" data-edit-product="${p.id}">Editar</button><button class="admin-button small danger" data-delete-product="${p.id}">Excluir</button></div></td></tr>`).join('')}</tbody></table></div></section>${editing}`}
function productEditor(id){const p=id?productById(id):{id:'',name:'',slug:'',category:categoryNames()[0]||'',brand:'',price:0,compareAt:0,stock:0,badge:'',accent:'#1677ff',description:'',sku:`JI-${String(state.data.products.length+1).padStart(3,'0')}`,rating:5,reviews:0,featured:false,active:true,image:''};return `<section class="admin-panel" id="productEditor"><div class="admin-panel__head"><div><h2>${id?'Editar produto':'Novo produto'}</h2><p>As alterações serão refletidas imediatamente na loja.</p></div><button class="admin-button" data-cancel-editor>Fechar</button></div><div class="admin-panel__body"><form class="admin-form" id="productAdminForm"><input type="hidden" name="id" value="${safe(p.id)}"><label>Nome<input name="name" required value="${safe(p.name)}"></label><label>SKU<input name="sku" required value="${safe(p.sku)}"></label><label>Categoria<select name="category">${categoryNames().map(c=>`<option ${p.category===c?'selected':''}>${safe(c)}</option>`).join('')}</select></label><label>Marca<input name="brand" value="${safe(p.brand)}"></label><label>Preço<input name="price" type="number" step="0.01" min="0" required value="${p.price}"></label><label>Preço anterior<input name="compareAt" type="number" step="0.01" min="0" value="${p.compareAt||''}"></label><label>Estoque<input name="stock" type="number" min="0" required value="${p.stock}"></label><label>Etiqueta<input name="badge" value="${safe(p.badge||'')}" placeholder="Oferta, novidade..."></label><label>Avaliação<input name="rating" type="number" min="0" max="5" step="0.1" value="${p.rating}"></label><label>Nº de avaliações<input name="reviews" type="number" min="0" value="${p.reviews}"></label><label>Cor do mockup<input name="accent" type="color" value="${safe(p.accent||'#1677ff')}"></label><label>URL da imagem<input name="image" value="${safe(p.image||'')}" placeholder="https://..."></label><label class="full">Enviar imagem<input type="file" id="productImageUpload" accept="image/*"></label><div class="full image-preview" id="productImagePreview">${p.image?`<img src="${safe(p.image)}" alt="Prévia">`:'Sem imagem: será usado o mockup automático.'}</div><label class="full">Descrição<textarea name="description">${safe(p.description)}</textarea></label><label class="switch-line"><input name="featured" type="checkbox" ${p.featured?'checked':''}>Produto em destaque</label><label class="switch-line"><input name="active" type="checkbox" ${p.active?'checked':''}>Produto visível</label><div class="admin-form-actions"><button type="button" class="admin-button" data-cancel-editor>Cancelar</button><button class="admin-button primary" type="submit">Salvar produto</button></div></form></div></section>`}
function adminBanners(){const editing=state.adminEditor?.type==='banner'?bannerEditor(state.adminEditor.id):'';return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Banners rotativos</h2><p>Controle imagem, texto, cores, ordem e visibilidade.</p></div><button class="admin-button primary" data-new-banner>Adicionar banner</button></div><div class="admin-panel__body"><div class="admin-list">${state.data.banners.sort((a,b)=>a.order-b.order).map(b=>`<div class="sortable-row" draggable="true" data-banner-row="${b.id}"><span class="drag-handle">⋮⋮</span><div class="sortable-row__main"><div class="banner-thumb" style="background-image:${b.image?`url('${safe(b.image)}')`:'none'};background-color:${safe(b.end)}"></div><div><strong>${safe(b.title)}</strong><small>${b.active?'Visível':'Oculto'} · posição ${b.order}</small></div></div><div class="sortable-row__actions"><button class="admin-button small" data-move-banner="up" data-id="${b.id}">↑</button><button class="admin-button small" data-move-banner="down" data-id="${b.id}">↓</button><button class="admin-button small" data-edit-banner="${b.id}">Editar</button><button class="admin-button small danger" data-delete-banner="${b.id}">Excluir</button></div></div>`).join('')}</div></div></section>${editing}`}
function bannerEditor(id){const b=id?state.data.banners.find(x=>x.id===id):{id:'',kicker:'NOVA CAMPANHA',title:'Título do novo banner.',highlight:'novo banner.',subtitle:'Descrição da campanha.',buttonText:'Ver produtos',buttonLink:'#catalogo',start:'#07101f',end:'#1677ff',image:'',active:true};return `<section class="admin-panel" id="bannerEditor"><div class="admin-panel__head"><div><h2>${id?'Editar banner':'Novo banner'}</h2><p>Imagens podem ser inseridas por URL ou upload local.</p></div><button class="admin-button" data-cancel-editor>Fechar</button></div><div class="admin-panel__body"><form class="admin-form" id="bannerAdminForm"><input type="hidden" name="id" value="${safe(b.id)}"><label>Chamada superior<input name="kicker" value="${safe(b.kicker)}"></label><label>Trecho destacado<input name="highlight" value="${safe(b.highlight)}"></label><label class="full">Título<input name="title" required value="${safe(b.title)}"></label><label class="full">Subtítulo<textarea name="subtitle">${safe(b.subtitle)}</textarea></label><label>Texto do botão<input name="buttonText" value="${safe(b.buttonText)}"></label><label>Link do botão<input name="buttonLink" value="${safe(b.buttonLink)}"></label><label>Cor inicial<input name="start" type="color" value="${safe(b.start)}"></label><label>Cor final<input name="end" type="color" value="${safe(b.end)}"></label><label class="full">URL da imagem<input name="image" value="${safe(b.image||'')}" placeholder="https://..."></label><label class="full">Enviar imagem<input type="file" id="bannerImageUpload" accept="image/*"></label><div class="full image-preview" id="bannerImagePreview">${b.image?`<img src="${safe(b.image)}" alt="Prévia">`:'Sem imagem: será usado o fundo em degradê.'}</div><label class="switch-line"><input name="active" type="checkbox" ${b.active?'checked':''}>Banner visível</label><div class="admin-form-actions"><button type="button" class="admin-button" data-cancel-editor>Cancelar</button><button class="admin-button primary" type="submit">Salvar banner</button></div></form></div></section>`}
function adminCategories(){return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Categorias</h2><p>Defina nomes, ordem e disponibilidade nos filtros.</p></div><button class="admin-button primary" data-new-category>Adicionar categoria</button></div><div class="admin-panel__body"><div class="admin-list">${state.data.categories.sort((a,b)=>a.order-b.order).map(c=>`<div class="sortable-row"><span class="drag-handle">⋮⋮</span><div class="sortable-row__main"><div><strong>${safe(c.name)}</strong><small>${state.data.products.filter(p=>p.category===c.name).length} produtos · ${c.active?'visível':'oculta'}</small></div></div><div class="sortable-row__actions"><button class="admin-button small" data-move-category="up" data-id="${c.id}">↑</button><button class="admin-button small" data-move-category="down" data-id="${c.id}">↓</button><button class="admin-button small" data-edit-category="${c.id}">Editar</button><button class="admin-button small danger" data-delete-category="${c.id}">Excluir</button></div></div>`).join('')}</div></div></section>${state.adminEditor?.type==='category'?categoryEditor(state.adminEditor.id):''}`}
function categoryEditor(id){const c=id?state.data.categories.find(x=>x.id===id):{id:'',name:'',active:true};return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>${id?'Editar categoria':'Nova categoria'}</h2></div></div><div class="admin-panel__body"><form class="admin-form" id="categoryAdminForm"><input type="hidden" name="id" value="${safe(c.id)}"><label class="full">Nome<input name="name" required value="${safe(c.name)}"></label><label class="switch-line"><input name="active" type="checkbox" ${c.active?'checked':''}>Categoria visível</label><div class="admin-form-actions"><button type="button" class="admin-button" data-cancel-editor>Cancelar</button><button class="admin-button primary" type="submit">Salvar categoria</button></div></form></div></section>`}
function adminSections(){const editing=state.adminEditor?.type==='section'?sectionEditor(state.adminEditor.id):'';return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Ordem da página inicial</h2><p>Reorganize e oculte seções completas da vitrine.</p></div></div><div class="admin-panel__body"><div class="admin-list">${state.data.sections.sort((a,b)=>a.order-b.order).map(s=>`<div class="sortable-row" draggable="true" data-section-row="${s.id}"><span class="drag-handle">⋮⋮</span><div class="sortable-row__main"><div><strong>${safe(s.name)}</strong><small>Posição ${s.order} · ${s.active?'visível':'oculta'}</small></div></div><div class="sortable-row__actions"><button class="admin-button small" data-move-section="up" data-id="${s.id}">↑</button><button class="admin-button small" data-move-section="down" data-id="${s.id}">↓</button><button class="admin-button small" data-toggle-section="${s.id}">${s.active?'Ocultar':'Exibir'}</button><button class="admin-button small" data-edit-section="${s.id}">Editar</button></div></div>`).join('')}</div></div></section>${editing}`}
function sectionEditor(id){const s=state.data.sections.find(x=>x.id===id);return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Editar ${safe(s.name)}</h2></div></div><div class="admin-panel__body"><form class="admin-form" id="sectionAdminForm"><input type="hidden" name="id" value="${safe(s.id)}"><label>Chamada superior<input name="eyebrow" value="${safe(s.eyebrow||'')}"></label><label>Nome interno<input name="name" value="${safe(s.name)}"></label><label class="full">Título<input name="title" value="${safe(s.title||'')}"></label><label class="full">Subtítulo<textarea name="subtitle">${safe(s.subtitle||'')}</textarea></label>${s.id==='promo'?`<label>Texto do botão<input name="buttonText" value="${safe(s.buttonText||'')}"></label><label>Link do botão<input name="buttonLink" value="${safe(s.buttonLink||'')}"></label>`:''}<div class="admin-form-actions"><button type="button" class="admin-button" data-cancel-editor>Cancelar</button><button class="admin-button primary" type="submit">Salvar seção</button></div></form></div></section>`}
function adminCoupons(){const editing=state.adminEditor?.type==='coupon'?couponEditor(state.adminEditor.id):'';return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Cupons de desconto</h2><p>Configure percentual, valor fixo, mínimo e validade.</p></div><button class="admin-button primary" data-new-coupon>Adicionar cupom</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Código</th><th>Tipo</th><th>Valor</th><th>Mínimo</th><th>Validade</th><th>Status</th><th>Ações</th></tr></thead><tbody>${state.data.coupons.map(c=>`<tr><td><strong>${safe(c.code)}</strong></td><td>${c.type==='percent'?'Percentual':'Valor fixo'}</td><td>${c.type==='percent'?`${c.value}%`:money(c.value)}</td><td>${money(c.min)}</td><td>${c.expires?new Date(`${c.expires}T12:00:00`).toLocaleDateString('pt-BR'):'Sem validade'}</td><td><span class="status-tag ${c.active?'':'off'}">${c.active?'Ativo':'Inativo'}</span></td><td><div class="admin-table-actions"><button class="admin-button small" data-edit-coupon="${c.id}">Editar</button><button class="admin-button small danger" data-delete-coupon="${c.id}">Excluir</button></div></td></tr>`).join('')}</tbody></table></div></section>${editing}`}
function couponEditor(id){const c=id?state.data.coupons.find(x=>x.id===id):{id:'',code:'',type:'percent',value:10,min:0,expires:'',active:true};return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>${id?'Editar cupom':'Novo cupom'}</h2></div></div><div class="admin-panel__body"><form class="admin-form" id="couponAdminForm"><input type="hidden" name="id" value="${safe(c.id)}"><label>Código<input name="code" required value="${safe(c.code)}"></label><label>Tipo<select name="type"><option value="percent" ${c.type==='percent'?'selected':''}>Percentual</option><option value="fixed" ${c.type==='fixed'?'selected':''}>Valor fixo</option></select></label><label>Valor<input name="value" type="number" min="0" step="0.01" value="${c.value}"></label><label>Pedido mínimo<input name="min" type="number" min="0" step="0.01" value="${c.min}"></label><label>Validade<input name="expires" type="date" value="${safe(c.expires||'')}"></label><label class="switch-line"><input name="active" type="checkbox" ${c.active?'checked':''}>Cupom ativo</label><div class="admin-form-actions"><button type="button" class="admin-button" data-cancel-editor>Cancelar</button><button class="admin-button primary" type="submit">Salvar cupom</button></div></form></div></section>`}
function adminOrders(){const detail=state.selectedOrder?orderDetail(state.selectedOrder):'';return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Pedidos demonstrativos</h2><p>Pedidos gerados no checkout deste navegador.</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Pagamento</th><th>Total</th><th>Status</th><th>Ações</th></tr></thead><tbody>${state.data.orders.map(o=>`<tr class="order-row"><td><strong>${safe(o.id)}</strong></td><td>${safe(o.customer.name)}</td><td>${dateBR(o.createdAt)}</td><td>${safe(o.payment)}</td><td>${money(o.total)}</td><td>${orderStatusTag(o.status)}</td><td><button class="admin-button small" data-view-order="${o.id}">Abrir</button></td></tr>`).join('')}</tbody></table></div></section>${detail}`}
function orderDetail(id){const o=state.data.orders.find(x=>x.id===id);if(!o)return'';return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Pedido ${safe(o.id)}</h2><p>${dateBR(o.createdAt)}</p></div><div class="admin-actions"><select class="admin-button" id="orderStatusSelect">${['Novo','Aguardando pagamento','Pago','Preparando','Enviado','Entregue','Cancelado'].map(status=>`<option ${o.status===status?'selected':''}>${status}</option>`).join('')}</select><button class="admin-button primary" data-save-order-status="${o.id}">Atualizar status</button></div></div><div class="admin-panel__body"><div class="order-details"><div class="order-box"><h3>Cliente</h3><p><strong>${safe(o.customer.name)}</strong></p><p>${safe(o.customer.email)}</p><p>${safe(o.customer.phone)}</p><p>${safe(o.customer.address)}</p><p>${safe(o.customer.city)}/${safe(o.customer.state)}</p></div><div class="order-box"><h3>Resumo</h3>${o.items.map(i=>`<div class="order-item"><span>${i.quantity}× ${safe(i.name)}</span><strong>${money(i.price*i.quantity)}</strong></div>`).join('')}<div class="order-item"><span>Desconto</span><strong>− ${money(o.discount)}</strong></div><div class="order-item"><span>Frete</span><strong>${money(o.shipping)}</strong></div><div class="order-item"><span>Total</span><strong>${money(o.total)}</strong></div></div></div></div></section>`}
function adminSettings(){const s=state.data.settings;return `<section class="admin-panel"><div class="admin-panel__head"><div><h2>Configurações da loja</h2><p>Dados gerais, frete, pagamento, tema e acesso.</p></div></div><div class="admin-panel__body"><form class="admin-form" id="settingsAdminForm"><label>Nome da loja<input name="storeName" value="${safe(s.storeName)}"></label><label>WhatsApp<input name="whatsapp" value="${safe(s.whatsapp)}"></label><label>E-mail<input name="email" type="email" value="${safe(s.email)}"></label><label>Horário<input name="hours" value="${safe(s.hours)}"></label><label class="full">Barra de anúncio<input name="announcement" value="${safe(s.announcement)}"></label><label class="full">Descrição do rodapé<input name="footerDescription" value="${safe(s.footerDescription)}"></label><label>Cor principal<input name="primaryColor" type="color" value="${safe(s.primaryColor)}"></label><label>Troca automática dos banners (segundos)<input name="autoBannerSeconds" type="number" min="3" max="30" value="${s.autoBannerSeconds}"></label><label>Frete fixo<input name="shippingFlat" type="number" min="0" step="0.01" value="${s.shippingFlat}"></label><label>Frete grátis acima de<input name="freeShippingThreshold" type="number" min="0" step="0.01" value="${s.freeShippingThreshold}"></label><label>Desconto no Pix (%)<input name="pixDiscount" type="number" min="0" max="100" step="0.1" value="${s.pixDiscount}"></label><label>PIN administrativo<input name="adminPin" type="password" required value="${safe(s.adminPin)}"></label><div class="admin-form-actions"><button class="admin-button primary" type="submit">Salvar configurações</button></div></form></div></section><section class="admin-panel"><div class="admin-panel__head"><div><h2>Itens de confiança</h2><p>Textos exibidos logo abaixo dos banners.</p></div></div><div class="admin-panel__body"><form class="admin-form" id="trustAdminForm">${state.data.trustItems.map((item,index)=>`<label>Título ${index+1}<input name="title-${index}" value="${safe(item.title)}"></label><label>Subtítulo ${index+1}<input name="subtitle-${index}" value="${safe(item.subtitle)}"></label>`).join('')}<div class="admin-form-actions"><button class="admin-button primary" type="submit">Salvar benefícios rápidos</button></div></form></div></section>`}
function adminData(){return `<div class="admin-inline-note">Este projeto usa localStorage. Exportar os dados é recomendado antes de limpar o navegador.</div><section class="admin-panel"><div class="admin-panel__head"><div><h2>Backup e manutenção</h2><p>Exporte, importe ou restaure o projeto demonstrativo.</p></div></div><div class="admin-panel__body"><div class="data-actions"><article class="data-card"><h3>Exportar dados</h3><p>Baixe produtos, banners, cupons, configurações e pedidos em JSON.</p><button class="admin-button primary" data-export>Exportar JSON</button></article><article class="data-card"><h3>Importar dados</h3><p>Restaure um arquivo JSON exportado anteriormente.</p><label class="admin-button" style="display:inline-flex;align-items:center">Selecionar arquivo<input id="adminImportFile" type="file" accept="application/json" hidden></label></article><article class="data-card"><h3>Limpar pedidos</h3><p>Apaga apenas os pedidos demonstrativos registrados.</p><button class="admin-button danger" data-clear-orders>Limpar pedidos</button></article><article class="data-card"><h3>Restaurar V3</h3><p>Volta produtos, banners e configurações ao estado inicial.</p><button class="admin-button danger" data-reset-data>Restaurar dados padrão</button></article><article class="data-card"><h3>Resumo técnico</h3><p>${state.data.products.length} produtos · ${state.data.banners.length} banners · ${state.data.orders.length} pedidos.</p><button class="admin-button" data-copy-summary>Copiar resumo</button></article></div></div></section>`}
function afterAdminRender(){const editor=$('#productEditor,#bannerEditor');if(editor)setTimeout(()=>editor.scrollIntoView({behavior:'smooth',block:'start'}),30);bindDragAndDrop();bindImageUploads()}
function moveItem(list,id,direction){const sorted=[...list].sort((a,b)=>a.order-b.order),index=sorted.findIndex(x=>x.id===id),target=direction==='up'?index-1:index+1;if(index<0||target<0||target>=sorted.length)return;[sorted[index],sorted[target]]=[sorted[target],sorted[index]];sorted.forEach((item,i)=>item.order=i+1);saveData();renderAdmin()}
function bindDragAndDrop(){let dragged=null;$$('[draggable="true"]',$('#adminContent')).forEach(row=>{row.addEventListener('dragstart',()=>{dragged=row;row.classList.add('dragging')});row.addEventListener('dragend',()=>{row.classList.remove('dragging');dragged=null});row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();if(!dragged||dragged===row)return;const type=dragged.dataset.productRow?'products':dragged.dataset.bannerRow?'banners':'sections',dragId=dragged.dataset.productRow||dragged.dataset.bannerRow||dragged.dataset.sectionRow,targetId=row.dataset.productRow||row.dataset.bannerRow||row.dataset.sectionRow,list=state.data[type].sort((a,b)=>a.order-b.order),from=list.findIndex(x=>x.id===dragId),to=list.findIndex(x=>x.id===targetId);const [item]=list.splice(from,1);list.splice(to,0,item);list.forEach((x,i)=>x.order=i+1);saveData();renderAdmin()})})}
function fileToDataUrl(file,callback){if(!file)return;const reader=new FileReader();reader.onload=()=>callback(reader.result);reader.readAsDataURL(file)}
function bindImageUploads(){const productUpload=$('#productImageUpload'),bannerUpload=$('#bannerImageUpload');if(productUpload)productUpload.onchange=e=>fileToDataUrl(e.target.files[0],url=>{const input=$('[name="image"]','#productAdminForm');input.value=url;$('#productImagePreview').innerHTML=`<img src="${url}" alt="Prévia">`});if(bannerUpload)bannerUpload.onchange=e=>fileToDataUrl(e.target.files[0],url=>{const input=$('[name="image"]','#bannerAdminForm');input.value=url;$('#bannerImagePreview').innerHTML=`<img src="${url}" alt="Prévia">`})}
function formDataObject(form){return Object.fromEntries(new FormData(form).entries())}
function saveProduct(form){const v=formDataObject(form),existing=v.id?productById(v.id):null,product={...(existing||{}),id:v.id||uid('product'),slug:slugify(v.name),name:v.name,sku:v.sku,category:v.category,brand:v.brand,price:Number(v.price),compareAt:Number(v.compareAt)||0,stock:Number(v.stock),badge:v.badge,accent:v.accent,description:v.description,rating:Number(v.rating)||0,reviews:Number(v.reviews)||0,image:v.image,featured:form.elements.featured.checked,active:form.elements.active.checked,order:existing?.order||state.data.products.length+1};if(existing)Object.assign(existing,product);else state.data.products.push(product);saveData();state.adminEditor=null;renderAdmin();toast('Produto salvo.')}
function saveBanner(form){const v=formDataObject(form),existing=v.id?state.data.banners.find(x=>x.id===v.id):null,banner={...(existing||{}),id:v.id||uid('banner'),kicker:v.kicker,title:v.title,highlight:v.highlight,subtitle:v.subtitle,buttonText:v.buttonText,buttonLink:v.buttonLink,start:v.start,end:v.end,image:v.image,active:form.elements.active.checked,order:existing?.order||state.data.banners.length+1};if(existing)Object.assign(existing,banner);else state.data.banners.push(banner);saveData();state.adminEditor=null;renderAdmin();toast('Banner salvo.')}
function saveCategory(form){const v=formDataObject(form),existing=v.id?state.data.categories.find(x=>x.id===v.id):null,old=existing?.name;const category={...(existing||{}),id:v.id||uid('cat'),name:v.name,active:form.elements.active.checked,order:existing?.order||state.data.categories.length+1};if(existing){Object.assign(existing,category);if(old!==v.name)state.data.products.filter(p=>p.category===old).forEach(p=>p.category=v.name)}else state.data.categories.push(category);saveData();state.adminEditor=null;renderAdmin();toast('Categoria salva.')}
function saveSection(form){const v=formDataObject(form),s=state.data.sections.find(x=>x.id===v.id);Object.assign(s,{name:v.name,eyebrow:v.eyebrow,title:v.title,subtitle:v.subtitle,buttonText:v.buttonText??s.buttonText,buttonLink:v.buttonLink??s.buttonLink});saveData();state.adminEditor=null;renderAdmin();toast('Seção salva.')}
function saveCoupon(form){const v=formDataObject(form),existing=v.id?state.data.coupons.find(x=>x.id===v.id):null,coupon={...(existing||{}),id:v.id||uid('coupon'),code:v.code.toUpperCase(),type:v.type,value:Number(v.value),min:Number(v.min),expires:v.expires,active:form.elements.active.checked};if(existing)Object.assign(existing,coupon);else state.data.coupons.push(coupon);saveData();state.adminEditor=null;renderAdmin();toast('Cupom salvo.')}
function exportData(){const blob=new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='junior-imports-v3-dados.json';a.click();URL.revokeObjectURL(url)}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{state.data=normalizeData(JSON.parse(reader.result));saveData('Dados importados');state.adminPage='dashboard';renderAdmin();toast('Dados importados com sucesso.')}catch{toast('Arquivo inválido.')}};reader.readAsText(file)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2300)}

function bindEvents(){
  $('#searchToggle').addEventListener('click',()=>{const open=$('#searchBar').classList.toggle('open');$('#searchToggle').setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>$('#globalSearch').focus(),100)});
  $('#searchClose').addEventListener('click',()=>{$('#searchBar').classList.remove('open');$('#searchToggle').setAttribute('aria-expanded','false')});
  $('#globalSearch').addEventListener('input',event=>{state.search=event.target.value;if($('#catalogo'))renderCatalogControls()});
  $('#mobileMenu').addEventListener('click',()=>{const open=$('#mobileNav').classList.toggle('open');$('#mobileMenu').setAttribute('aria-expanded',String(open))});
  $('#mobileNav').addEventListener('click',()=>$('#mobileNav').classList.remove('open'));
  $('#heroPrev').addEventListener('click',()=>showBanner(state.bannerIndex-1));$('#heroNext').addEventListener('click',()=>showBanner(state.bannerIndex+1));
  $('#heroDots').addEventListener('click',e=>{const dot=e.target.closest('[data-banner-dot]');if(dot)showBanner(Number(dot.dataset.bannerDot))});
  document.addEventListener('click',event=>{
    const favorite=event.target.closest('[data-favorite]');if(favorite){event.stopPropagation();toggleFavorite(favorite.dataset.favorite);return}
    const add=event.target.closest('[data-add-product]');if(add){event.stopPropagation();addToCart(add.dataset.addProduct);return}
    const view=event.target.closest('[data-view-product]');if(view&&!event.target.closest('[data-add-product]'))openProduct(view.dataset.viewProduct);
    const cat=event.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;renderCatalogControls()}
    if(event.target.closest('#clearFilters')){state.category='Todos';state.search='';$('#globalSearch').value='';renderCatalogControls()}
  });
  $('#homeSections').addEventListener('change',e=>{if(e.target.id==='sortSelect'){state.sort=e.target.value;renderCatalogControls()}});
  $('#cartToggle').addEventListener('click',openDrawer);$('#cartDrawer').addEventListener('click',e=>{if(e.target.closest('[data-close="cart"]'))closeDrawer();const plus=e.target.closest('[data-cart-plus]'),minus=e.target.closest('[data-cart-minus]'),remove=e.target.closest('[data-cart-remove]');if(plus)updateCart(plus.dataset.cartPlus,1);if(minus)updateCart(minus.dataset.cartMinus,-1);if(remove)removeCart(remove.dataset.cartRemove)});
  $('#cartApplyCoupon').addEventListener('click',applyCoupon);$('#clearCart').addEventListener('click',()=>{state.cart=[];state.coupon=null;saveCart();renderCart()});$('#checkoutButton').addEventListener('click',openCheckout);
  $('#productModal').addEventListener('click',e=>{if(e.target.closest('[data-close="product"]'))closeModal('#productModal');const qty=e.target.closest('[data-product-qty]');if(qty){const p=productById($('[data-modal-add]').dataset.modalAdd);state.productQuantity=Math.max(1,Math.min(p.stock,state.productQuantity+(qty.dataset.productQty==='plus'?1:-1)));$('#productQty').textContent=state.productQuantity}const add=e.target.closest('[data-modal-add]');if(add){addToCart(add.dataset.modalAdd,state.productQuantity);closeModal('#productModal');openDrawer()}});
  $('#checkoutModal').addEventListener('click',e=>{if(e.target.closest('[data-close="checkout"]'))closeModal('#checkoutModal')});$('#checkoutForm').addEventListener('change',e=>{if(e.target.name==='payment')renderCheckout(e.target.value)});$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();showOrderSuccess(createOrder(formDataObject(e.currentTarget)))});
  $('#orderSuccessModal').addEventListener('click',e=>{if(e.target.closest('[data-close="success"]'))closeModal('#orderSuccessModal')});
  $('#adminToggle').addEventListener('click',openAdmin);$('#adminLoginClose').addEventListener('click',closeAdmin);$('#adminLoginButton').addEventListener('click',enterAdmin);$('#adminResetPin').addEventListener('click',resetAdminPin);$('#adminPin').addEventListener('input',()=>{const error=$('#adminPinError');if(error)error.textContent=''});$('#adminPin').addEventListener('keydown',e=>{if(e.key==='Enter')enterAdmin()});$('#adminClose').addEventListener('click',closeAdmin);$('#adminViewStore').addEventListener('click',closeAdmin);$('#adminLogout').addEventListener('click',()=>{closeAdmin();state.adminPage='dashboard'});$('#adminMenuToggle').addEventListener('click',()=>$('.admin-sidebar').classList.toggle('open'));
  $('#adminNav').addEventListener('click',e=>{const btn=e.target.closest('[data-admin-page]');if(!btn)return;state.adminPage=btn.dataset.adminPage;state.adminEditor=null;state.selectedOrder=null;$('.admin-sidebar').classList.remove('open');renderAdmin()});
  $('#adminContent').addEventListener('click',adminClickHandler);$('#adminContent').addEventListener('submit',adminSubmitHandler);$('#adminContent').addEventListener('change',e=>{if(e.target.id==='adminImportFile'&&e.target.files[0])importData(e.target.files[0])});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#adminShell').classList.contains('open'))closeAdmin();else{$$('.modal.open').forEach(m=>closeModal(`#${m.id}`));closeDrawer()}}});
}
function adminClickHandler(e){
  const go=e.target.closest('[data-admin-go]');if(go){state.adminPage=go.dataset.adminGo;renderAdmin();return}
  if(e.target.closest('[data-new-product]')){state.adminEditor={type:'product',id:null};renderAdmin();return}const editP=e.target.closest('[data-edit-product]');if(editP){state.adminEditor={type:'product',id:editP.dataset.editProduct};renderAdmin();return}const delP=e.target.closest('[data-delete-product]');if(delP&&confirm('Excluir este produto?')){state.data.products=state.data.products.filter(p=>p.id!==delP.dataset.deleteProduct);state.cart=state.cart.filter(i=>i.id!==delP.dataset.deleteProduct);saveData();saveCart();renderAdmin();return}const moveP=e.target.closest('[data-move-product]');if(moveP){moveItem(state.data.products,moveP.dataset.id,moveP.dataset.moveProduct);return}
  if(e.target.closest('[data-new-banner]')){state.adminEditor={type:'banner',id:null};renderAdmin();return}const editB=e.target.closest('[data-edit-banner]');if(editB){state.adminEditor={type:'banner',id:editB.dataset.editBanner};renderAdmin();return}const delB=e.target.closest('[data-delete-banner]');if(delB&&confirm('Excluir este banner?')){state.data.banners=state.data.banners.filter(b=>b.id!==delB.dataset.deleteBanner);saveData();renderAdmin();return}const moveB=e.target.closest('[data-move-banner]');if(moveB){moveItem(state.data.banners,moveB.dataset.id,moveB.dataset.moveBanner);return}
  if(e.target.closest('[data-new-category]')){state.adminEditor={type:'category',id:null};renderAdmin();return}const editC=e.target.closest('[data-edit-category]');if(editC){state.adminEditor={type:'category',id:editC.dataset.editCategory};renderAdmin();return}const delC=e.target.closest('[data-delete-category]');if(delC){const c=state.data.categories.find(x=>x.id===delC.dataset.deleteCategory);if(state.data.products.some(p=>p.category===c.name)){toast('Mova os produtos desta categoria antes de excluir.');return}if(confirm('Excluir esta categoria?')){state.data.categories=state.data.categories.filter(x=>x.id!==c.id);saveData();renderAdmin()}return}const moveC=e.target.closest('[data-move-category]');if(moveC){moveItem(state.data.categories,moveC.dataset.id,moveC.dataset.moveCategory);return}
  const editS=e.target.closest('[data-edit-section]');if(editS){state.adminEditor={type:'section',id:editS.dataset.editSection};renderAdmin();return}const toggleS=e.target.closest('[data-toggle-section]');if(toggleS){const s=state.data.sections.find(x=>x.id===toggleS.dataset.toggleSection);s.active=!s.active;saveData();renderAdmin();return}const moveS=e.target.closest('[data-move-section]');if(moveS){moveItem(state.data.sections,moveS.dataset.id,moveS.dataset.moveSection);return}
  if(e.target.closest('[data-new-coupon]')){state.adminEditor={type:'coupon',id:null};renderAdmin();return}const editCoupon=e.target.closest('[data-edit-coupon]');if(editCoupon){state.adminEditor={type:'coupon',id:editCoupon.dataset.editCoupon};renderAdmin();return}const delCoupon=e.target.closest('[data-delete-coupon]');if(delCoupon&&confirm('Excluir este cupom?')){state.data.coupons=state.data.coupons.filter(c=>c.id!==delCoupon.dataset.deleteCoupon);saveData();renderAdmin();return}
  const viewO=e.target.closest('[data-view-order]');if(viewO){state.selectedOrder=viewO.dataset.viewOrder;renderAdmin();return}const saveStatus=e.target.closest('[data-save-order-status]');if(saveStatus){const o=state.data.orders.find(x=>x.id===saveStatus.dataset.saveOrderStatus);o.status=$('#orderStatusSelect').value;saveData();renderAdmin();toast('Status atualizado.');return}
  if(e.target.closest('[data-cancel-editor]')){state.adminEditor=null;renderAdmin();return}if(e.target.closest('[data-export]')){exportData();return}if(e.target.closest('[data-clear-orders]')&&confirm('Apagar todos os pedidos demonstrativos?')){state.data.orders=[];state.selectedOrder=null;saveData();renderAdmin();return}if(e.target.closest('[data-reset-data]')&&confirm('Restaurar todos os dados padrão da V3?')){state.data=clone(DEFAULT_DATA);state.cart=[];state.coupon=null;saveData();saveCart();state.adminPage='dashboard';renderAdmin();return}if(e.target.closest('[data-copy-summary]')){navigator.clipboard?.writeText(`${state.data.products.length} produtos, ${state.data.banners.length} banners e ${state.data.orders.length} pedidos demonstrativos.`);toast('Resumo copiado.');return}
}
function adminSubmitHandler(e){e.preventDefault();if(e.target.id==='productAdminForm')saveProduct(e.target);else if(e.target.id==='bannerAdminForm')saveBanner(e.target);else if(e.target.id==='categoryAdminForm')saveCategory(e.target);else if(e.target.id==='sectionAdminForm')saveSection(e.target);else if(e.target.id==='couponAdminForm')saveCoupon(e.target);else if(e.target.id==='settingsAdminForm'){const v=formDataObject(e.target);Object.assign(state.data.settings,{...v,shippingFlat:Number(v.shippingFlat),freeShippingThreshold:Number(v.freeShippingThreshold),pixDiscount:Number(v.pixDiscount),autoBannerSeconds:Number(v.autoBannerSeconds)});saveData();renderAdmin();toast('Configurações salvas.')}else if(e.target.id==='trustAdminForm'){state.data.trustItems.forEach((item,index)=>{item.title=e.target[`title-${index}`].value;item.subtitle=e.target[`subtitle-${index}`].value});saveData();renderAdmin();toast('Itens atualizados.')}
}

renderStore();bindEvents();
