"use client";

import { Eye, EyeOff, ImagePlus, Pencil, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { useAdminData } from "./admin-data-provider";
import { AdminPanel, StatusTag } from "./admin-ui";
import { bannerSchema } from "@/lib/validation";
import type { Banner } from "@/types/store";

export function BannersAdmin() {
  const { data, deleteBanner, moveItem, toggleItem } = useAdminData();
  const [editing, setEditing] = useState<Banner | "new" | null>(null);
  const banners = [...data.banners].sort((a, b) => a.order - b.order);
  return <><AdminPanel title="Banners rotativos" description="Controle imagem, texto, cores, ordem e visibilidade." action={<button className="admin-button primary" onClick={() => setEditing("new")}><Plus /> Adicionar banner</button>}><div className="admin-list">{banners.map((banner, index) => <article className="sortable-row" key={banner.id}><div className="order-buttons"><button disabled={index === 0} onClick={() => moveItem("banners", banner.id, -1)}>↑</button><button disabled={index === banners.length - 1} onClick={() => moveItem("banners", banner.id, 1)}>↓</button></div><div className="banner-thumb" style={{ backgroundImage: banner.imageUrl ? `url(${banner.imageUrl})` : undefined, background: banner.imageUrl ? undefined : `linear-gradient(120deg, ${banner.startColor}, ${banner.endColor})` }} /><div className="sortable-main"><strong>{banner.title}</strong><small>Posição {banner.order} · <StatusTag active={banner.active}>{banner.active ? "Visível" : "Oculto"}</StatusTag></small></div><div className="admin-actions"><button onClick={() => toggleItem("banners", banner.id)}>{banner.active ? <EyeOff /> : <Eye />}</button><button onClick={() => setEditing(banner)}><Pencil /></button><button className="danger" onClick={() => window.confirm("Excluir este banner?") && deleteBanner(banner.id)}><Trash2 /></button></div></article>)}</div></AdminPanel>{editing && <BannerEditor banner={editing === "new" ? null : editing} onClose={() => setEditing(null)} />}</>;
}

function BannerEditor({ banner, onClose }: { banner: Banner | null; onClose: () => void }) {
  const { data, saveBanner, uploadMedia } = useAdminData();
  const [form, setForm] = useState<Banner>(banner ?? { id: crypto.randomUUID(), kicker: "NOVA CAMPANHA", title: "Título do novo banner.", highlight: "novo banner.", subtitle: "Descrição da campanha.", buttonText: "Ver produtos", buttonLink: "#catalogo", startColor: "#07101f", endColor: "#1677ff", imageUrl: "", active: true, order: data.banners.length + 1 });
  const [error, setError] = useState("");
  const [uploading, setUploading] = useState(false);
  function field<K extends keyof Banner>(key: K, value: Banner[K]) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: React.FormEvent) { event.preventDefault(); const parsed = bannerSchema.safeParse(form); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Revise os campos."); return; } await saveBanner(form); onClose(); }
  return <div className="admin-modal" role="dialog" aria-modal="true"><button className="admin-modal-overlay" onClick={onClose} aria-label="Fechar" /><div className="admin-modal-panel"><header><div><span>BANNERS</span><h2>{banner ? "Editar banner" : "Novo banner"}</h2></div><button onClick={onClose}><X /></button></header><form className="admin-form" onSubmit={submit}><label>Chamada superior<input value={form.kicker} onChange={(event) => field("kicker", event.target.value)} /></label><label>Trecho destacado<input value={form.highlight} onChange={(event) => field("highlight", event.target.value)} /></label><label className="full">Título<input value={form.title} onChange={(event) => field("title", event.target.value)} /></label><label className="full">Subtítulo<textarea value={form.subtitle} onChange={(event) => field("subtitle", event.target.value)} /></label><label>Texto do botão<input value={form.buttonText} onChange={(event) => field("buttonText", event.target.value)} /></label><label>Link do botão<input value={form.buttonLink} onChange={(event) => field("buttonLink", event.target.value)} /></label><label>Cor inicial<input type="color" value={form.startColor} onChange={(event) => field("startColor", event.target.value)} /></label><label>Cor final<input type="color" value={form.endColor} onChange={(event) => field("endColor", event.target.value)} /></label><label className="full">URL da imagem<input value={form.imageUrl} onChange={(event) => field("imageUrl", event.target.value)} /></label><label className="full upload-label"><ImagePlus /> {uploading ? "Enviando..." : "Enviar imagem"}<input type="file" accept="image/*" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { field("imageUrl", await uploadMedia(file, "banner-media")); } finally { setUploading(false); } }} /></label><label className="check-field"><input type="checkbox" checked={form.active} onChange={(event) => field("active", event.target.checked)} /> Banner visível</label>{error && <p className="admin-form-error full">{error}</p>}<div className="admin-form-actions full"><button type="button" className="admin-button" onClick={onClose}>Cancelar</button><button className="admin-button primary" type="submit">Salvar banner</button></div></form></div></div>;
}
