"use client";

import { IconBuildingStore, IconCircleCheck, IconPackage, IconPlus, IconTruckDelivery } from "@tabler/icons-react";
import { useState } from "react";
import { formatDateTime, formatMoney } from "@/lib/format";
import { supplierSchema } from "@/lib/validation";
import type { PurchaseOrder, Supplier } from "@/types/store";
import { useAdminData } from "./admin-data-provider";
import { AdminEmpty, AdminPanel } from "./admin-ui";

const purchaseStatusLabels: Record<PurchaseOrder["status"], string> = { draft: "Rascunho", ordered: "Pedido enviado", partial: "Recebimento parcial", received: "Recebido", cancelled: "Cancelado" };

export function PurchasingAdmin() {
  const { data, saveSupplier, savePurchaseOrder, receivePurchaseOrder } = useAdminData();
  const [supplierOpen, setSupplierOpen] = useState(false);
  const [orderOpen, setOrderOpen] = useState(false);
  const [error, setError] = useState("");
  const [supplier, setSupplier] = useState<Supplier>(() => ({ id: crypto.randomUUID(), name: "", taxId: "", email: "", phone: "", leadTimeDays: 7, notes: "", active: true, createdAt: new Date().toISOString() }));
  const [orderForm, setOrderForm] = useState({ supplierId: "", productId: "", quantity: 1, unitCost: 0, expectedAt: "", lotCode: "", expiryDate: "", notes: "" });
  const orderedValue = data.purchaseOrders.filter((order) => ["ordered", "partial"].includes(order.status)).reduce((sum, order) => sum + order.total, 0);

  async function submitSupplier(event: React.FormEvent) {
    event.preventDefault(); const parsed = supplierSchema.safeParse(supplier); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Revise o fornecedor."); return; }
    await saveSupplier(supplier); setSupplier({ id: crypto.randomUUID(), name: "", taxId: "", email: "", phone: "", leadTimeDays: 7, notes: "", active: true, createdAt: new Date().toISOString() }); setSupplierOpen(false); setError("");
  }

  async function submitOrder(event: React.FormEvent) {
    event.preventDefault(); const product = data.products.find((item) => item.id === orderForm.productId); if (!orderForm.supplierId || !product || orderForm.quantity < 1 || orderForm.unitCost <= 0) { setError("Selecione fornecedor e produto e informe quantidade e custo válidos."); return; }
    const id = crypto.randomUUID(); const itemId = crypto.randomUUID(); const total = orderForm.quantity * orderForm.unitCost;
    const order: PurchaseOrder = { id, code: `OC-${String(1001 + data.purchaseOrders.length)}`, supplierId: orderForm.supplierId, status: "ordered", expectedAt: orderForm.expectedAt, receivedAt: "", total, notes: orderForm.notes, items: [{ id: itemId, productId: product.id, name: product.name, quantity: orderForm.quantity, unitCost: orderForm.unitCost, lotCode: orderForm.lotCode, expiryDate: orderForm.expiryDate }], createdAt: new Date().toISOString() };
    await savePurchaseOrder(order); setOrderForm({ supplierId: "", productId: "", quantity: 1, unitCost: 0, expectedAt: "", lotCode: "", expiryDate: "", notes: "" }); setOrderOpen(false); setError("");
  }

  return <div className="ops-page"><section className="ops-hero"><div><span>ERP · COMPRAS</span><h2>Reposição organizada do pedido ao recebimento.</h2><p>Cadastre fornecedores, acompanhe ordens e atualize estoque, lotes, custo e contas a pagar em uma única ação.</p></div><div className="ops-hero-actions"><button className="admin-button" onClick={() => { setSupplierOpen(true); setOrderOpen(false); }}><IconBuildingStore /> Novo fornecedor</button><button className="admin-button primary" onClick={() => { setOrderOpen(true); setSupplierOpen(false); }} disabled={!data.suppliers.length}><IconPlus /> Nova ordem</button></div></section>
    <section className="ops-metric-grid"><article><span className="blue"><IconBuildingStore /></span><div><small>Fornecedores ativos</small><strong>{data.suppliers.filter((item) => item.active).length}</strong><p>base de compras</p></div></article><article><span className="warning"><IconTruckDelivery /></span><div><small>Em trânsito</small><strong>{data.purchaseOrders.filter((item) => ["ordered", "partial"].includes(item.status)).length}</strong><p>{formatMoney(orderedValue)} em pedidos</p></div></article><article><span className="green"><IconCircleCheck /></span><div><small>Recebidas</small><strong>{data.purchaseOrders.filter((item) => item.status === "received").length}</strong><p>estoque atualizado</p></div></article><article><span className="purple"><IconPackage /></span><div><small>Itens solicitados</small><strong>{data.purchaseOrders.reduce((sum, order) => sum + order.items.reduce((itemSum, item) => itemSum + item.quantity, 0), 0)}</strong><p>em todas as ordens</p></div></article></section>
    {supplierOpen && <AdminPanel title="Cadastrar fornecedor" description="Centralize contatos, prazo médio e observações de compra."><form className="ops-form" onSubmit={submitSupplier}><label className="wide">Nome<input value={supplier.name} onChange={(event) => setSupplier((current) => ({ ...current, name: event.target.value }))} /></label><label>Documento<input value={supplier.taxId} onChange={(event) => setSupplier((current) => ({ ...current, taxId: event.target.value }))} /></label><label>E-mail<input type="email" value={supplier.email} onChange={(event) => setSupplier((current) => ({ ...current, email: event.target.value }))} /></label><label>Telefone<input value={supplier.phone} onChange={(event) => setSupplier((current) => ({ ...current, phone: event.target.value }))} /></label><label>Prazo médio (dias)<input type="number" min="0" value={supplier.leadTimeDays} onChange={(event) => setSupplier((current) => ({ ...current, leadTimeDays: Number(event.target.value) }))} /></label><label className="wide">Observações<textarea rows={3} value={supplier.notes} onChange={(event) => setSupplier((current) => ({ ...current, notes: event.target.value }))} /></label>{error && <p className="admin-form-error wide">{error}</p>}<div className="ops-form-actions wide"><button type="button" className="admin-button" onClick={() => setSupplierOpen(false)}>Cancelar</button><button className="admin-button primary">Salvar fornecedor</button></div></form></AdminPanel>}
    {orderOpen && <AdminPanel title="Nova ordem de compra" description="O recebimento atualizará estoque, lote, custo e financeiro automaticamente."><form className="ops-form" onSubmit={submitOrder}><label>Fornecedor<select value={orderForm.supplierId} onChange={(event) => setOrderForm((current) => ({ ...current, supplierId: event.target.value }))}><option value="">Selecione</option>{data.suppliers.filter((item) => item.active).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Produto<select value={orderForm.productId} onChange={(event) => { const product = data.products.find((item) => item.id === event.target.value); setOrderForm((current) => ({ ...current, productId: event.target.value, unitCost: product?.costPrice ?? 0 })); }}><option value="">Selecione</option>{data.products.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Quantidade<input type="number" min="1" value={orderForm.quantity} onChange={(event) => setOrderForm((current) => ({ ...current, quantity: Number(event.target.value) }))} /></label><label>Custo unitário<input type="number" min="0.01" step="0.01" value={orderForm.unitCost} onChange={(event) => setOrderForm((current) => ({ ...current, unitCost: Number(event.target.value) }))} /></label><label>Previsão<input type="date" value={orderForm.expectedAt} onChange={(event) => setOrderForm((current) => ({ ...current, expectedAt: event.target.value }))} /></label><label>Lote<input value={orderForm.lotCode} onChange={(event) => setOrderForm((current) => ({ ...current, lotCode: event.target.value }))} /></label><label>Validade<input type="date" value={orderForm.expiryDate} onChange={(event) => setOrderForm((current) => ({ ...current, expiryDate: event.target.value }))} /></label><label className="wide">Observações<input value={orderForm.notes} onChange={(event) => setOrderForm((current) => ({ ...current, notes: event.target.value }))} /></label><div className="purchase-total wide"><span>Total estimado</span><strong>{formatMoney(orderForm.quantity * orderForm.unitCost)}</strong></div>{error && <p className="admin-form-error wide">{error}</p>}<div className="ops-form-actions wide"><button type="button" className="admin-button" onClick={() => setOrderOpen(false)}>Cancelar</button><button className="admin-button primary">Criar ordem de compra</button></div></form></AdminPanel>}
    <div className="ops-two-columns purchasing-layout"><AdminPanel title="Ordens de compra" description="Acompanhe prazos e receba sem lançamentos duplicados."><div className="purchase-order-list">{data.purchaseOrders.map((order) => <article key={order.id}><header><div><span>{order.code}</span><strong>{data.suppliers.find((item) => item.id === order.supplierId)?.name ?? "Fornecedor"}</strong></div><b className={order.status}>{purchaseStatusLabels[order.status]}</b></header><div>{order.items.map((item) => <p key={item.id}>{item.quantity}x {item.name} · {formatMoney(item.unitCost)}</p>)}</div><footer><div><strong>{formatMoney(order.total)}</strong><small>Criada em {formatDateTime(order.createdAt)}{order.expectedAt ? ` · previsão ${order.expectedAt}` : ""}</small></div>{["ordered", "partial"].includes(order.status) && <button className="admin-button primary" onClick={() => void receivePurchaseOrder(order.id)}><IconCircleCheck /> Receber compra</button>}</footer></article>)}{!data.purchaseOrders.length && <AdminEmpty><IconTruckDelivery /><strong>Nenhuma ordem de compra.</strong><span>Crie a primeira reposição.</span></AdminEmpty>}</div></AdminPanel><section className="supplier-list"><header><div><h3>Fornecedores</h3><p>Contatos e prazos de fornecimento.</p></div></header>{data.suppliers.map((item) => <article key={item.id}><div><strong>{item.name}</strong><small>{item.email || item.phone || "Sem contato"}</small></div><span>{item.leadTimeDays} dias</span></article>)}{!data.suppliers.length && <AdminEmpty><IconBuildingStore /><strong>Nenhum fornecedor.</strong></AdminEmpty>}</section></div>
  </div>;
}
